spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    database: mysql
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  datasource:
    url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
    username: "root"
    password: "root"
    dbcp2:
      test-while-idle: true
      validation-query: "SELECT 1"
server:
  port: 8082