spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    database: mysql
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  datasource:
    url: "jdbc:mysql://localhost:3306/itemsharingdatabase?createDatabaseIfNotExist=true"
    username: "root"
    password: "root"
    dbcp2:
      test-while-idle: true
      validation-query: "SELECT 1"
  application:
    name: userservice

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG

